---
repositories:
  - name: dagster
    url: https://dagster-io.github.io/helm
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

releases:
  - name: monster-secrets
    namespace: dagster
    chart: datarepo-helm/create-secret-manager-secret
    missingFileHandler: Warn
    values:
      - secrets:
          - secretName: monster-dagster-secrets
            nameSpace: dagster
            vals:
              - kubeSecretKey: SLACK_TOKEN
                path: secret/dsde/monster/{{ requiredEnv "ENV" }}/ingest/dap/dagster
                vaultKey: slack-token
  - name: monster-dog-aging-ingest
    namespace: dagster
    chart: dagster/dagster-user-deployments
    values:
      - deployments:
        - name: "monster-dap-ingest"
          image:
            repository: "us.gcr.io/broad-dsp-gcr-public/monster-dap-dagster"
            tag: {{ requiredEnv "GIT_SHORTHASH" | quote }}
            pullPolicy: Always
          dagsterApiGrpcArgs:
            - "-f"
            - 'dap_orchestration/repositories/{{ requiredEnv "ENV" }}_repositories.py'
          port: 3030
          envSecrets:
            - name: monster-dagster-secrets
          envConfigMaps:
            # we can't use values.yaml to insert env vars into deployments, since overwriting lists
            # doesn't work in helmfiles. instead, like above, we just tell it to use the daemon's config map.
            - name: monster-dagster-daemon-env

        serviceAccount:
          create: false
          name: monster-dagster
