scala_project: dog-aging-hles-extraction
# todo: should this be "target_class: org.broadinstitute.monster.dap"?
target_class: org.broadinstitute.monster.dap.cslb.CslbExtractionPipeline
additional_args:
  - api_token:
      env: REDCAP_API_TOKEN
region: us-central1
worker_machine_type: n1-standard-1
autoscaling_algorithm: THROUGHPUT_BASED
num_workers: 4
max_num_workers: 8