# todo: hardcode this to be relative to the solid that’s configuring it by getting the dir from the configured solid
working_dir: ../
region: us-east1
worker_machine_type: n1-standard-1
autoscaling_algorithm: THROUGHPUT_BASED
num_workers: 4
max_num_workers: 8
