temp_bucket: broad-dsp-monster-dap-prod-temp-storage
service_account: dap-dataflow-runner@exemplary-proxy-308717.iam.gserviceaccount.com
project: exemplary-proxy-308717
image_name: us.gcr.io/broad-dsp-gcr-public/dog-aging-hles-transformation
