package org.broadinstitute.monster.dap.environment

import org.broadinstitute.monster.dap.RawRecord
import org.broadinstitute.monster.dogaging.jadeschema.fragment.EnvironmentTemperaturePrecipitation

object TemperaturePrecipitationTransformations {

  /**
    * Parse all temperature and precipitation variables out of a raw RedCap record,
    * injecting them into a partially-modeled environment record.
    */
  def mapTemperaturePrecipitationVariables(
    rawRecord: RawRecord
  ): EnvironmentTemperaturePrecipitation = {
    EnvironmentTemperaturePrecipitation(
      tpDataYear = rawRecord.getOptionalNumber("tp_data_year"),
      tpPcpnAnnual01 = rawRecord.getOptional("tp_pcpn_annual_01").map(_.toDouble),
      tpPcpnAnnual02 = rawRecord.getOptional("tp_pcpn_annual_02").map(_.toDouble),
      tpPcpnAnnual03 = rawRecord.getOptional("tp_pcpn_annual_03").map(_.toDouble),
      tpPcpnAnnual04 = rawRecord.getOptional("tp_pcpn_annual_04").map(_.toDouble),
      tpPcpnAnnual05 = rawRecord.getOptional("tp_pcpn_annual_05").map(_.toDouble),
      tpPcpnAnnual06 = rawRecord.getOptional("tp_pcpn_annual_06").map(_.toDouble),
      tpPcpnAnnual07 = rawRecord.getOptional("tp_pcpn_annual_07").map(_.toDouble),
      tpPcpnAnnual08 = rawRecord.getOptional("tp_pcpn_annual_08").map(_.toDouble),
      tpPcpnAnnual09 = rawRecord.getOptional("tp_pcpn_annual_09").map(_.toDouble),
      tpPcpnAnnual10 = rawRecord.getOptional("tp_pcpn_annual_10").map(_.toDouble),
      tpPcpnAnnual11 = rawRecord.getOptional("tp_pcpn_annual_11").map(_.toDouble),
      tpPcpnAnnual12 = rawRecord.getOptional("tp_pcpn_annual_12").map(_.toDouble),
      tpTmpcAnnual01 = rawRecord.getOptional("tp_tmpc_annual_01").map(_.toDouble),
      tpTmpcAnnual02 = rawRecord.getOptional("tp_tmpc_annual_02").map(_.toDouble),
      tpTmpcAnnual03 = rawRecord.getOptional("tp_tmpc_annual_03").map(_.toDouble),
      tpTmpcAnnual04 = rawRecord.getOptional("tp_tmpc_annual_04").map(_.toDouble),
      tpTmpcAnnual05 = rawRecord.getOptional("tp_tmpc_annual_05").map(_.toDouble),
      tpTmpcAnnual06 = rawRecord.getOptional("tp_tmpc_annual_06").map(_.toDouble),
      tpTmpcAnnual07 = rawRecord.getOptional("tp_tmpc_annual_07").map(_.toDouble),
      tpTmpcAnnual08 = rawRecord.getOptional("tp_tmpc_annual_08").map(_.toDouble),
      tpTmpcAnnual09 = rawRecord.getOptional("tp_tmpc_annual_09").map(_.toDouble),
      tpTmpcAnnual10 = rawRecord.getOptional("tp_tmpc_annual_10").map(_.toDouble),
      tpTmpcAnnual11 = rawRecord.getOptional("tp_tmpc_annual_11").map(_.toDouble),
      tpTmpcAnnual12 = rawRecord.getOptional("tp_tmpc_annual_12").map(_.toDouble),
      tpTmaxAnnual01 = rawRecord.getOptional("tp_tmax_annual_01").map(_.toDouble),
      tpTmaxAnnual02 = rawRecord.getOptional("tp_tmax_annual_02").map(_.toDouble),
      tpTmaxAnnual03 = rawRecord.getOptional("tp_tmax_annual_03").map(_.toDouble),
      tpTmaxAnnual04 = rawRecord.getOptional("tp_tmax_annual_04").map(_.toDouble),
      tpTmaxAnnual05 = rawRecord.getOptional("tp_tmax_annual_05").map(_.toDouble),
      tpTmaxAnnual06 = rawRecord.getOptional("tp_tmax_annual_06").map(_.toDouble),
      tpTmaxAnnual07 = rawRecord.getOptional("tp_tmax_annual_07").map(_.toDouble),
      tpTmaxAnnual08 = rawRecord.getOptional("tp_tmax_annual_08").map(_.toDouble),
      tpTmaxAnnual09 = rawRecord.getOptional("tp_tmax_annual_09").map(_.toDouble),
      tpTmaxAnnual10 = rawRecord.getOptional("tp_tmax_annual_10").map(_.toDouble),
      tpTmaxAnnual11 = rawRecord.getOptional("tp_tmax_annual_11").map(_.toDouble),
      tpTmaxAnnual12 = rawRecord.getOptional("tp_tmax_annual_12").map(_.toDouble),
      tpTminAnnual01 = rawRecord.getOptional("tp_tmin_annual_01").map(_.toDouble),
      tpTminAnnual02 = rawRecord.getOptional("tp_tmin_annual_02").map(_.toDouble),
      tpTminAnnual03 = rawRecord.getOptional("tp_tmin_annual_03").map(_.toDouble),
      tpTminAnnual04 = rawRecord.getOptional("tp_tmin_annual_04").map(_.toDouble),
      tpTminAnnual05 = rawRecord.getOptional("tp_tmin_annual_05").map(_.toDouble),
      tpTminAnnual06 = rawRecord.getOptional("tp_tmin_annual_06").map(_.toDouble),
      tpTminAnnual07 = rawRecord.getOptional("tp_tmin_annual_07").map(_.toDouble),
      tpTminAnnual08 = rawRecord.getOptional("tp_tmin_annual_08").map(_.toDouble),
      tpTminAnnual09 = rawRecord.getOptional("tp_tmin_annual_09").map(_.toDouble),
      tpTminAnnual10 = rawRecord.getOptional("tp_tmin_annual_10").map(_.toDouble),
      tpTminAnnual11 = rawRecord.getOptional("tp_tmin_annual_11").map(_.toDouble),
      tpTminAnnual12 = rawRecord.getOptional("tp_tmin_annual_12").map(_.toDouble),
      tpNormDataYear = rawRecord.getOptionalNumber("tp_norm_data_year"),
      tpPcpnNorm01 = rawRecord.getOptional("tp_pcpn_norm_01").map(_.toDouble),
      tpPcpnNorm02 = rawRecord.getOptional("tp_pcpn_norm_02").map(_.toDouble),
      tpPcpnNorm03 = rawRecord.getOptional("tp_pcpn_norm_03").map(_.toDouble),
      tpPcpnNorm04 = rawRecord.getOptional("tp_pcpn_norm_04").map(_.toDouble),
      tpPcpnNorm05 = rawRecord.getOptional("tp_pcpn_norm_05").map(_.toDouble),
      tpPcpnNorm06 = rawRecord.getOptional("tp_pcpn_norm_06").map(_.toDouble),
      tpPcpnNorm07 = rawRecord.getOptional("tp_pcpn_norm_07").map(_.toDouble),
      tpPcpnNorm08 = rawRecord.getOptional("tp_pcpn_norm_08").map(_.toDouble),
      tpPcpnNorm09 = rawRecord.getOptional("tp_pcpn_norm_09").map(_.toDouble),
      tpPcpnNorm10 = rawRecord.getOptional("tp_pcpn_norm_10").map(_.toDouble),
      tpPcpnNorm11 = rawRecord.getOptional("tp_pcpn_norm_11").map(_.toDouble),
      tpPcpnNorm12 = rawRecord.getOptional("tp_pcpn_norm_12").map(_.toDouble),
      tpTmpcNorm01 = rawRecord.getOptional("tp_tmpc_norm_01").map(_.toDouble),
      tpTmpcNorm02 = rawRecord.getOptional("tp_tmpc_norm_02").map(_.toDouble),
      tpTmpcNorm03 = rawRecord.getOptional("tp_tmpc_norm_03").map(_.toDouble),
      tpTmpcNorm04 = rawRecord.getOptional("tp_tmpc_norm_04").map(_.toDouble),
      tpTmpcNorm05 = rawRecord.getOptional("tp_tmpc_norm_05").map(_.toDouble),
      tpTmpcNorm06 = rawRecord.getOptional("tp_tmpc_norm_06").map(_.toDouble),
      tpTmpcNorm07 = rawRecord.getOptional("tp_tmpc_norm_07").map(_.toDouble),
      tpTmpcNorm08 = rawRecord.getOptional("tp_tmpc_norm_08").map(_.toDouble),
      tpTmpcNorm09 = rawRecord.getOptional("tp_tmpc_norm_09").map(_.toDouble),
      tpTmpcNorm10 = rawRecord.getOptional("tp_tmpc_norm_10").map(_.toDouble),
      tpTmpcNorm11 = rawRecord.getOptional("tp_tmpc_norm_11").map(_.toDouble),
      tpTmpcNorm12 = rawRecord.getOptional("tp_tmpc_norm_12").map(_.toDouble),
      tpTmaxNorm01 = rawRecord.getOptional("tp_tmax_norm_01").map(_.toDouble),
      tpTmaxNorm02 = rawRecord.getOptional("tp_tmax_norm_02").map(_.toDouble),
      tpTmaxNorm03 = rawRecord.getOptional("tp_tmax_norm_03").map(_.toDouble),
      tpTmaxNorm04 = rawRecord.getOptional("tp_tmax_norm_04").map(_.toDouble),
      tpTmaxNorm05 = rawRecord.getOptional("tp_tmax_norm_05").map(_.toDouble),
      tpTmaxNorm06 = rawRecord.getOptional("tp_tmax_norm_06").map(_.toDouble),
      tpTmaxNorm07 = rawRecord.getOptional("tp_tmax_norm_07").map(_.toDouble),
      tpTmaxNorm08 = rawRecord.getOptional("tp_tmax_norm_08").map(_.toDouble),
      tpTmaxNorm09 = rawRecord.getOptional("tp_tmax_norm_09").map(_.toDouble),
      tpTmaxNorm10 = rawRecord.getOptional("tp_tmax_norm_10").map(_.toDouble),
      tpTmaxNorm11 = rawRecord.getOptional("tp_tmax_norm_11").map(_.toDouble),
      tpTmaxNorm12 = rawRecord.getOptional("tp_tmax_norm_12").map(_.toDouble),
      tpTminNorm01 = rawRecord.getOptional("tp_tmin_norm_01").map(_.toDouble),
      tpTminNorm02 = rawRecord.getOptional("tp_tmin_norm_02").map(_.toDouble),
      tpTminNorm03 = rawRecord.getOptional("tp_tmin_norm_03").map(_.toDouble),
      tpTminNorm04 = rawRecord.getOptional("tp_tmin_norm_04").map(_.toDouble),
      tpTminNorm05 = rawRecord.getOptional("tp_tmin_norm_05").map(_.toDouble),
      tpTminNorm06 = rawRecord.getOptional("tp_tmin_norm_06").map(_.toDouble),
      tpTminNorm07 = rawRecord.getOptional("tp_tmin_norm_07").map(_.toDouble),
      tpTminNorm08 = rawRecord.getOptional("tp_tmin_norm_08").map(_.toDouble),
      tpTminNorm09 = rawRecord.getOptional("tp_tmin_norm_09").map(_.toDouble),
      tpTminNorm10 = rawRecord.getOptional("tp_tmin_norm_10").map(_.toDouble),
      tpTminNorm11 = rawRecord.getOptional("tp_tmin_norm_11").map(_.toDouble),
      tpTminNorm12 = rawRecord.getOptional("tp_tmin_norm_12").map(_.toDouble)
    )
  }
}
