name: Master Validation and Release
on:
  push:
    branches:
      - master
jobs:
  master-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch tag history
        run: git fetch --tags
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@20.0.0
      - name: Check formatting
        run: sbt scalafmtCheckAll
        env:
          JVM_OPTS: -Xmx6144m -Xms6144m -Xss16m
      - name: Compile
        run: sbt Compile/compile Test/compile IntegrationTest/compile
        env:
          JVM_OPTS: -Xmx6144m -Xms6144m -Xss16m
      - name: Test
        run: sbt "set ThisBuild/coverageEnabled := true" test IntegrationTest/test coverageAggregate
        env:
          VAULT_ADDR: ${{ secrets.VaultAddress }}
          VAULT_ROLE_ID: ${{ secrets.VaultRoleId }}
          VAULT_SECRET_ID: ${{ secrets.VaultSecretId }}
          JVM_OPTS: -Xmx6144m -Xms6144m -Xss16m
      - name: Publish coverage
        uses: codecov/codecov-action@v1
      - uses: google-github-actions/setup-gcloud@main
        with:
          version: '286.0.0'
          project_id: broad-dsp-monster-dev
          service_account_email: jenkins-gcr-pusher@broad-dsp-monster-dev.iam.gserviceaccount.com
          service_account_key: ${{ secrets.Base64ServiceAccountKey }}
          export_default_credentials: true
      - name: Setup GCR auth
        run: gcloud auth configure-docker --quiet
      - name: Publish
        run: sbt publish
        env:
          JVM_OPTS: -Xmx6144m -Xms6144m -Xss16m
      - name: Get artifact slug
        id: get-artifact-slug
        run: 'echo ::set-output name=slug::$(git rev-parse --short "$GITHUB_SHA")'
      - name: Push Dagster User Code Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./orchestration
          push: true
          tags: us.gcr.io/broad-dsp-gcr-public/monster-dap-dagster:${{steps.get-artifact-slug.outputs.slug}}

