name: PR Validation
on:
  pull_request:
    branches:
      - master
jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@20.0.0
      - name: Check formatting
        run: sbt scalafmtCheckAll
        env:
          JVM_OPTS: -Xmx6144m -Xms6144m -Xss16m
      - name: Compile
        run: sbt Compile/compile Test/compile IntegrationTest/compile
        env:
          JVM_OPTS: -Xmx6144m -Xms6144m -Xss16m
      - name: Test
        run: sbt "set ThisBuild/coverageEnabled := true" test IntegrationTest/test coverageAggregate doc
        env:
          VAULT_ADDR: ${{ secrets.VaultAddress }}
          VAULT_ROLE_ID: ${{ secrets.VaultRoleId }}
          VAULT_SECRET_ID: ${{ secrets.VaultSecretId }}
          JVM_OPTS: -Xmx6144m -Xms6144m -Xss16m
      - name: Publish coverage
        uses: codecov/codecov-action@v1
